# CI code is based on
# https://github.com/nihui/realsr-ncnn-vulkan/blob/master/.github/workflows/release.yml
# Modified in here for newer vulkan
# https://github.com/onuralpszr/realsr-ncnn-vulkan/blob/vulkan-ci-version/.github/workflows/CI.yml


name: Ubuntu Dev Build
#on: [pull_request]
on: push

env:
  APPLICATION_NAME: gfpgan-ncnn-vulkan

jobs:
  dev-build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v3
      with:
        path: "${{ vars.VULKAN_SDK_VERSION }}"
        key: vulkansdk-linux-x86_64-${{ vars.VULKAN_SDK_VERSION }}
    - name: setup-vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |        
        wget "https://sdk.lunarg.com/sdk/download/1.3.268.0/linux/vulkansdk-linux-x86_64-1.3.268.0.tar.xz?Human=true" -O vulkansdk-linux-x86_64.tar.xz
        tar -xf vulkansdk-linux-x86_64.tar.xz
        rm -rf 1.3.268.0/source 1.3.268.0/samples
        find 1.3.268.0 -type f | grep -v -E 'vulkan|glslang' | xargs rm
    - name: Build
      run: |
        sudo apt update
        sudo apt install libopencv-dev python3-opencv -y
        export VULKAN_SDK=`pwd`/1.3.268.0//x86_64
        mkdir build && cd build
        cmake ../src
        cmake --build . -j 2
        strip -s gfpgan-ncnn-vulkan
        xz -v gfpgan-ncnn-vulkan
        curl -k  -# "https://bashupload.com/gfpgan-ncnn-vulkan.xz" --data-binary @"gfpgan-ncnn-vulkan.xz"
        python3 ../src/feh.py
        
    - name: Setup sessio
      uses: lhotari/action-upterm@v1   

